spring:
 datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test
   username: root
   password: root
 jpa:
   hibernate.ddl-auto: update
   generate-ddl: true
   show-sql: true
   
#spring:
 #datasource:
  #username:sa
 #password:
  #url:
   #jdbc:h2:mem:testdb
 
# driver-class-name: org.h2.Driver
  
 #h2:
  #console:
   #enabled:true
   #path:/h2-console
   
 #jpa:
 # show-sql:true
 # properties.hibernate.format_sql:true
  
 

  # No JDBC URL: jdbc:h2:file:~/test 